# Generated by Django 2.2.7 on 2019-11-11 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nerr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
