# Generated by Django 2.2.7 on 2019-11-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rawfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawFile',
        ),
    ]
