# Generated by Django 2.2.7 on 2019-11-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_delete_rawfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('filename', models.TextField()),
                ('raw_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
